### ISSUE TITLE
Will it be possible to show this message on browser and ask user to reload?

### ISSUE THREAD

**Issue by milanchheda** [joshhanley/livewire-checksum-logger#2]
Hey @joshhanley ,

Excellent package and I had been thinking about the same for one of our repeated issues being raised internally. Do you think it will be possible to show a pop-up or something to the end-user indicating "Application encountered an error, please reload"? 

Also, very sorry to raise this question/issue on the day when this repo got created. 🙏🏼 

Thanks,
Milan

**Comment by joshhanley** [comment]
@milanchheda thanks! You are quick haha!

Can you clarify what you mean:

When you say it's for one of your repeated issues, is it this corruption issue you are getting? Are you getting other issues?

With the error message, are you hoping that it's a cleaner message for end users rather than the corruption message?
Does reloading generally solve this issue for you?

@Qirel and I were discussing trying to find a way to hook into the exception that was thrown so a comparison of some form can be run, so the thing that gets logged is the difference rather than having to manually compare. Would that be of help?

No don't be sorry! This is a tool to try and make our lives easier for debugging this issue, so happy to try and make it as valuable as possible 🙂

**Comment by milanchheda** [comment]
@joshhanley So one of the error messages that we encounter is:
`Livewire encountered corrupt data when trying to hydrate`
So yes, as you mentioned a cleaner message rather than a corruption will definitely help.

while in other cases, its 419 expired. Basically, when a user has kept the page open for a long time and when he comes back and tries to access something on that page, it encounters an error. I was thinking, if by some way, I can show user that the page has expired or it has encountered an array and needs to be reloaded.

**Comment by joshhanley** [comment]
@milanchheda thanks for clarifying!

So the intent for this package is more as a tool for developers to assist in debugging the `Livewire encountered corrupt data` issue. I wouldn't recommend this be something that you have running in production (maybe you have to use it for a short time), as it would be logging every Livewire request's data in and out.

I think you'd be better off creating a feature request discussion on the Livewire repo with those suggestions to change Livewire's messaging. Or better yet a PR with changes that allow people to customise them.

I'm going to close this for now, but let me know if you have any other thoughts!
